version: "3.1"

networks:
  requestify:
    driver: bridge

services:
  # Redis Cache
  redis:
    container_name: requestify-redis
    build: redis
    networks:
      - requestify
    ports:
      - 6370:6379
    volumes:
      - ./data/redis:/data
  # MongoDB Server instance
  mongo:
    container_name: requestify-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - requestify
    volumes:
      - ./data/mongo:/data
  # MongoDB web inspector
  mongo-express:
    container_name: requestify-mongo-express
    image: mongo-express
    restart: always
    networks:
      - requestify
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

